### PR TITLE
Add sockct close v2

### PR DESCRIPTION
**Pull request by yangrudan**
### What changes were proposed in this pull request?

1. add socket close action;
2. fix request misspell.

### Why are the changes needed?

1. avoid resoure leaks.

### Does this PR introduce any user-facing change?

No.

### How was this patch tested?

By run unit test.

### CODE REVIEW

**Comment by yangrudan** [comment]
@workingloong **How to supply exception testing?**

**Review by workingloong — APPROVED** [review]
LGTM

**Comment by workingloong** [comment]
> @workingloong **How to supply exception testing?**

You can patch the [method ](https://github.com/intelligent-machine-learning/dlrover/pull/1168/files#diff-a530d2bc0337355d7e29a93e763c955e68b969437f8ac4df30bfca2d70cf6f88R68)of socket in your test cases to raise an OSError like
https://github.com/intelligent-machine-learning/dlrover/blob/0c18cc5c82c9500de5a7c1b3e5b0f330a6a52aed/dlrover/python/tests/test_elastic_training_agent.py#L202-L207

**Comment by BalaBalaYi** [comment]
@yangrudan Please resolve the conflicts.

**Review by workingloong — APPROVED** [review]
LGTM

**Pull request merged**
