### PR TITLE
Examples: Add nanogpt jupyter notebook example.

### PR DESCRIPTION
**Pull request by ruirui-zhang**
### What changes were proposed in this pull request?

Please describe the changes you have made or proposed in this pull request.

### Why are the changes needed?
Explain the purpose or motivation behind these changes. What problem are you trying to solve?

- the notebook version nanogpt example provides a linear logical way to demonstrate the training process, making it easier for ds and mle to follow.

### Does this PR introduce any user-facing change?

Specify whether this pull request introduces any changes that users will directly interact with or notice.

- the pull request introduce a notebook for nanogpt training example, providing cpu and gpu ways to train-from-scratch, resume fine tune from a checkpoint, lora fine tuning and train using gpt2 model, using shakespeare data set as the training data set.

### How was this patch tested?
Detail the testing process you have undertaken to ensure the changes in this pull request are valid and working as intended.

pre-commit: shellcheck bash linter failed.
dlrover/python/tests & dlrover/trainer/tests: No module named xxx error

### CODE REVIEW

**Comment by Antlera** [comment]
LGTM

**Review by Antlera — COMMENTED** [review]
There are many additions up to 2633 lines.  We may split them into several shorter commits. It will help us review better.

**Comment by matmua** [comment]
We may attempt to optimize some details:
    1.Regarding the project directory, since we will have multiple notebook code examples for different models later on, perhaps we can consider creating a comprehensive notebook directory instead of "nanogpt_notebook." 
    2. Perhaps we can try running this notebook again in the "dlrover/examples/pytorch/notebook" directory. The current "input_file_path" appears to be displaying a private path, rather than a path for future customers.
    3.  Maybe we could delete the last two empty cells. 
    4.  "import lora", maybe need the relative path

**Comment by workingloong** [comment]
It is better to rename `examples/pytorch/nanogpt_notebook/train.ipynb` to `examples/pytorch/nanogpt/notebook/train.ipynb` or `examples/pytorch/nanogpt/train.ipynb`

**Pull request closed without merging**
