### PR TITLE
Examples: Add nanogpt jupyter notebook example.

### PR DESCRIPTION
**Pull request by ruirui-zhang**
### What changes were proposed in this pull request?

Added notebook version of nanogpt example.

### Why are the changes needed?

Provide notebook example for DS / MLE, help them go through the code in a linear logic.

### Does this PR introduce any user-facing change?

Users are going to run a dlrover notebook version.

### How was this patch tested?

All test passed.

### CODE REVIEW

**Comment by merlintang** [comment]
can you provide the google colab link for us to rerun this notebook

**Comment by ruirui-zhang** [comment]
https://drive.google.com/file/d/1q38VJMsEBVn7hEQ2pMoJ36QTbkSfdbJ8/view?usp=sharing

**Comment by merlintang** [comment]
this notebook is mess up.

https://colab.research.google.com/drive/1q38VJMsEBVn7hEQ2pMoJ36QTbkSfdbJ8#scrollTo=c9023b9d

**Comment by merlintang** [comment]
close since no further action

**Pull request closed without merging**
