### PR TITLE
Update the nanoGPT Guide

### PR DESCRIPTION
**Pull request by SylviaSyp**
### What changes were proposed in this pull request?

prepare the data for training.

### Why are the changes needed?

these changes provide the essential data required for effective model training.

### Does this PR introduce any user-facing change?

yes，this enhancement facilitates users in conveniently initiating model training.

### How was this patch tested?

this patch was tested by seamlessly incorporating the data file and updating the documentation accordingly.

### CODE REVIEW

**Review by Antlera — COMMENTED** [review]
LGTM

**Comment by SylviaSyp** [comment]
Yes, that's reasonable. I've already made the necessary changes.

**Comment by SylviaSyp** [comment]
> 40,000 lines are too many. 2000 lines may be enough to run a demo example.

Yes, that's reasonable. I've already made the necessary changes.

**Review by workingloong — APPROVED** [review]
LGTM

**Pull request merged**
