### PR TITLE
Add the WeChat group name.

### PR DESCRIPTION
**Pull request by workingloong**

### CODE REVIEW

**Review by merlintang — CHANGES_REQUESTED** [review]
if we want to have a community group, we can add the mail list, slack and wechat group together.

**Comment by Tonyhao96** [comment]
How to join this group? Would you please share the QR code? Thanks

**Comment by workingloong** [comment]
> 

image

**Comment by workingloong** [comment]
> How to join this group? Would you please share the QR code? Thanks

微信上你能通过“DLRover社区交流群” 搜索到吗？

**Comment by Tonyhao96** [comment]
> > How to join this group? Would you please share the QR code? Thanks
> 
> 微信上你能通过“DLRover社区交流群” 搜索到吗？

搜索不到，已通过QR Code加群，谢谢！

**Pull request closed without merging**
